# Generated by Django 3.2.16 on 2023-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
